### ISSUE TITLE
Type hinting in lil_aretomo screws help in tomo_preprocessing

### ISSUE THREAD

**Issue by shahpnmlab** [EuanPyle/lil_aretomo#20]
Hi Euan,

When i try to run relion_align_tilt_series IMOD:fiducials --help (from yours and Alister's tomo_preprocessing package). I see the following error.

relion_tomo_align_tilt_series IMOD --help
Traceback (most recent call last):
  File "softwares_for_all/anaconda3/bin/relion_tomo_align_tilt_series", line 33, in <module>
    sys.exit(load_entry_point('tomography-preprocessing', 'console_scripts', 'relion_tomo_align_tilt_series')())
  File "softwares_for_all/anaconda3/bin/relion_tomo_align_tilt_series", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/well/strubi/dce358/softwares_for_all/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/well/strubi/dce358/softwares_for_all/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "softwares_for_all/tomo_preprocessing/tomography_preprocessing/tilt_series_alignment/__init__.py", line 2, in <module>
    from .imod import batch_fiducials as _batch_imod_fiducials
  File "softwares_for_all/tomo_preprocessing/tomography_preprocessing/tilt_series_alignment/imod/__init__.py", line 1, in <module>
    from .batch_fiducials import batch_fiducials
  File "softwares_for_all/tomo_preprocessing/tomography_preprocessing/tilt_series_alignment/imod/batch_fiducials.py", line 8, in <module>
    import tomography_preprocessing.tilt_series_alignment.aretomo._utils
  File "softwares_for_all/tomo_preprocessing/tomography_preprocessing/tilt_series_alignment/aretomo/__init__.py", line 1, in <module>
    from .batch import batch_aretomo
  File "softwares_for_all/tomo_preprocessing/tomography_preprocessing/tilt_series_alignment/aretomo/batch.py", line 8, in <module>
    from .alignment import align_single_tilt_series
  File "softwares_for_all/tomo_preprocessing/tomography_preprocessing/tilt_series_alignment/aretomo/alignment.py", line 4, in <module>
    from lil_aretomo import run_aretomo_alignment
  File "/well/strubi/dce358/softwares_for_all/anaconda3/lib/python3.8/site-packages/lil_aretomo/__init__.py", line 1, in <module>
    from .aretomo import run_aretomo_alignment
  File "/well/strubi/dce358/softwares_for_all/anaconda3/lib/python3.8/site-packages/lil_aretomo/aretomo.py", line 5, in <module>
    from .utils import (
  File "/well/strubi/dce358/softwares_for_all/anaconda3/lib/python3.8/site-packages/lil_aretomo/utils.py", line 35, in <module>
    n_patches_xy: tuple[int, int],
TypeError: 'type' object is not subscriptable

Could you check where things are different in lil_aretomo that causes this error message to be displayed in tomo_preprocessing?

**Comment by EuanPyle** [comment]
Sure i'll have a look into it now!

**Comment by EuanPyle** [comment]
No probs, it's already done ;)! Will PR in a few mins

**Comment by alisterburt** [comment]
Closed by #25

**Comment by EuanPyle** [comment]
@shahpnmlab bug should be fixed now, install the latest version of lil_aretomo with: pip install lil-aretomo --upgrade; (should be v0.0.10) and reinstall the latest version of tomo_pp too, thanks! Let me know if there's anything else that goes wrong

**Comment by shahpnmlab** [comment]
Great! Go Team!
